export enum FloodReportType {
  FLOODED_ROAD = 'FLOODED_ROAD',
  RISING_WATER = 'RISING_WATER',
  FALLEN_TREE = 'FALLEN_TREE',
  POWER_OUT = 'POWER_OUT',
  LANDSLIDE = 'LANDSLIDE',
  TRAFFIC_BLOCKED = 'TRAFFIC_BLOCKED',
  OTHER = 'OTHER',
}
