export enum InfraType {
  MANHOLE = 'MANHOLE',
  DRAIN_LINE = 'DRAIN_LINE',
  CANAL = 'CANAL',
  LEVEE = 'LEVEE',
  PUMPING_STATION = 'PUMPING_STATION',
  SHELTER = 'SHELTER',
  WASTE_SITE = 'WASTE_SITE',
  TREE = 'TREE',
}
