import { Province } from './province';
import { AdministrativeUnit } from './administrative-unit';
import { SosRequest } from './sos-request';
import { RescueTeam } from './rescue-team';
import { User } from './user';
import { CasualtyStatus } from '../enums/casualtyStatus.enum';
import { Gender } from '../enums/gender.enum';
import { IncidentCause } from '../enums/incidentCause.enum';

export class Casualty {
  id: number;
  provinceId: number;
  adminUnitId: number;
  sosRequestId?: number;
  rescueTeamId?: number;
  reporterId?: number;
  location: any; // geometry;
  incidentAt?: Date;
  status: CasualtyStatus;
  victimName?: string;
  victimNationalId?: string;
  victimAge?: number;
  victimGender?: Gender | null;
  victimAddress?: string;
  victimUserId?: number;
  injuryDescription?: string;
  cause: IncidentCause;
  hospitalTransferredTo?: string;
  notes?: string;
  imageUrls: string;
  isConfirmed: boolean;
  confirmedBy?: number;
  confirmedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
  createdBy?: number;
  updatedBy?: number;
  province: Province;
  adminUnit: AdministrativeUnit;
  sosRequest?: SosRequest | null;
  rescueTeam?: RescueTeam | null;
  reporter?: User | null;
  confirmer?: User | null;
  victim?: User | null;
}
