import { Province } from './province';
import { AdministrativeUnit } from './administrative-unit';
import { UserRole } from './user-role';
import { Role } from './role';
import { HouseholdProfile } from './household-profile';
import { RescueTeamMember } from './rescue-team-member';
import { RescueTeam } from './rescue-team';
import { DutyLog } from './duty-log';
import { TeamAchievement } from './team-achievement';
import { SosRequest } from './sos-request';
import { FloodReport } from './flood-report';
import { Casualty } from './casualty';
import { DisasterEvent } from './disaster-event';
import { Donation } from './donation';
import { DonationCampaign } from './donation-campaign';
import { Message } from './message';
import { MessageRead } from './message-read';
import { FloodZone } from './flood-zone';
import { InfrastructureLayer } from './infrastructure-layer';
import { WeatherAlert } from './weather-alert';
import { IotDevice } from './iot-device';
import { AuditLog } from './audit-log';
import { Device } from './device';
import { Permission } from './permission';
import { Gender } from '../enums/gender.enum';

export class User {
  id: number;
  provinceId: number;
  adminUnitId?: number;
  fullName: string;
  nationalId: string;
  nationalIdVerified: boolean;
  dateOfBirth: Date;
  gender: Gender;
  phone: string;
  phoneVerified: boolean;
  email?: string;
  emailVerified: boolean;
  password?: string;
  avatarUrl?: string;
  nationalIdFrontUrl?: string;
  nationalIdBackUrl?: string;
  addressDetail?: string;
  homeLocation?: any; // geometry;
  currentLocation?: any; // geometry;
  trustScore: number;
  isVerified: boolean;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
  lastSeenAt?: Date;
  deletedAt?: Date;
  province: Province;
  adminUnit?: AdministrativeUnit | null;
  userRoles: UserRole[];
  rolesCreated: Role[];
  householdProfile?: HouseholdProfile | null;
  rescueTeamMember?: RescueTeamMember | null;
  leaderOfTeams: RescueTeam[];
  dutyLogs: DutyLog[];
  achievementsAwarded: TeamAchievement[];
  sosRequests: SosRequest[];
  sosAssigned: SosRequest[];
  sosResolved: SosRequest[];
  floodReports: FloodReport[];
  floodVerified: FloodReport[];
  casualtiesReported: Casualty[];
  casualtiesConfirmed: Casualty[];
  casualtiesVictim: Casualty[];
  disasterEventsCreated: DisasterEvent[];
  donations: Donation[];
  donationsReceived: Donation[];
  donationsDistributed: Donation[];
  campaignsCreated: DonationCampaign[];
  messagesSent: Message[];
  messageReads: MessageRead[];
  floodZonesUpdated: FloodZone[];
  infrastructureUpdated: InfrastructureLayer[];
  weatherAlertsTriggered: WeatherAlert[];
  iotDevices: IotDevice[];
  auditLogs: AuditLog[];
  devices: Device[];
  permissionsCreated: Permission[];
  permissionsUpdated: Permission[];
}
